SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
build-type: group
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by:
- BUILD_TESTS
- BUILD_VALIDATIONTESTS
includes:
- ${BSP_INCLUDES}
install: []
ldflags: []
links:
- role: build-dependency
  uid: libvalidation
- role: build-dependency
  uid: validation-0
- role: build-dependency
  uid: validation-1
- role: build-dependency
  uid: model-0
type: build
use-after:
- validation
- rtemstest
use-before: []
